In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('../data/advertising.csv')

In [3]:
X = df.drop(columns=['Sales']).values
y = df['Sales'].values

In [4]:
std_scl = StandardScaler()
make_poly = PolynomialFeatures(degree=3, include_bias=False)
lin_reg = LinearRegression()

In [5]:
X_2 = std_scl.fit_transform(X)
X_2[:5]

array([[ 0.96985227,  0.98152247,  1.77894547],
       [-1.19737623,  1.08280781,  0.66957876],
       [-1.51615499,  1.52846331,  1.78354865],
       [ 0.05204968,  1.21785493,  1.28640506],
       [ 0.3941822 , -0.84161366,  1.28180188]])

In [6]:
X_3 = (X[:, 2] - np.mean(X[:, 2])) / np.sqrt(np.sum((X[:, 2] - np.mean(X[:, 2]))**2) / len(X))
X_3

array([ 1.77894547,  0.66957876,  1.78354865,  1.28640506,  1.28180188,
        2.04592999, -0.32470841, -0.87248699, -1.36042422, -0.43058158,
       -0.29248614, -1.22232878,  1.62704048, -1.07502697,  0.71100739,
        1.02862691,  3.84117072,  1.16211917, -0.56407384, -0.52724839,
        1.05164281, -0.32470841,  0.87672192, -0.20042252, -0.56407384,
       -0.50883567, -0.82645518, -0.3523275 , -0.3523275 ,  0.47164196,
        0.58211831,  0.37037197, -0.02550162, -1.39264649, -1.06582061,
       -1.01518562, -1.17629696,  0.69719785,  0.20926062,  0.066562  ,
        0.04814928,  0.37497515, -1.32359877, -0.19121615,  0.5867215 ,
        0.0435461 ,  0.23687971, -0.55486748,  0.89053147,  0.28751471,
        0.18624472, -1.2407415 ,  0.41640379,  1.29561142, -0.6745502 ,
        1.35545278,  0.49926105, -0.64232793,  0.32894334, -0.97836017,
       -0.42137522,  1.11148417, -0.14978752, -1.0197888 , -0.07613662,
       -1.3650274 , -1.30518604, -0.93693153, -0.90010608, -0.15

In [7]:
np.sum(X_2[:, 2] == X_3)

np.int64(200)

In [8]:
len(X_3)

200

In [9]:
X_4 = make_poly.fit_transform(X_2)
X_4[0:1]

array([[0.96985227, 0.98152247, 1.77894547, 0.94061342, 0.95193179,
        1.72531429, 0.96338636, 1.74607495, 3.16464698, 0.91225606,
        0.92323321, 1.67329998, 0.93434245, 1.69343475, 3.06924004,
        0.94558536, 1.7138118 , 3.10617212, 5.62973439]])